version: '2'

services:
 nginx:
  image: nginx:latest
  ports:
   - "3000:80"
   - "3001:443"
  volumes:
   - ./hosts:/etc/nginx/conf.d
   - ./www:/var/www
   - ./logs:/var/log/nginx
  links:
   - php
 php:
  build: ./images
  volumes:
   - ./www:/var/www

